export const allItems = {
  separators: [
    { name: 'Cutmaster 5000', price: 4200, currency: '$', url: 'cutter.png' },
    { name: 'GrindPro X', price: 3870, currency: '$', url: 'cutter.png' },
    { name: 'Meatify Turbo', price: 5120, currency: '$', url: 'cutter.png' },
    { name: 'SlicerXpert', price: 4680, currency: '$', url: 'cutter.png' },
    { name: 'ChopMonster', price: 4790, currency: '$', url: 'cutter.png' },
    { name: 'MincedBeast 300', price: 3990, currency: '$', url: 'cutter.png' },
    { name: 'BladeCrafter', price: 5320, currency: '$', url: 'cutter.png' },
    { name: 'Grindzilla', price: 5500, currency: '$', url: 'cutter.png' },
  ],
  cutters: [
    { name: 'TenderMatic', price: 3620, currency: '$', url: 'cutter.png' },
    { name: 'MaxMeat XR', price: 4590, currency: '$', url: 'cutter.png' },
    { name: 'SlaughterPro', price: 3950, currency: '$', url: 'cutter.png' },
    { name: 'SliceCore 88', price: 4220, currency: '$', url: 'cutter.png' },
    { name: 'MinceForge', price: 4850, currency: '$', url: 'cutter.png' },
    { name: 'CarnaCraft', price: 4090, currency: '$', url: 'cutter.png' },
    { name: 'GrindEdge', price: 4470, currency: '$', url: 'cutter.png' },
    { name: 'UltraChopper', price: 4730, currency: '$', url: 'cutter.png' },
    { name: 'BeefBreaker', price: 3900, currency: '$', url: 'cutter.png' },
    { name: 'SliceLord 7', price: 5200, currency: '$', url: 'cutter.png' },
    { name: 'MechMincer', price: 4110, currency: '$', url: 'cutter.png' },
    { name: 'BladeBot 2000', price: 4530, currency: '$', url: 'cutter.png' },
    { name: 'MeatSaw Pro', price: 3820, currency: '$', url: 'cutter.png' },
    { name: 'AutoCutter Z', price: 4300, currency: '$', url: 'cutter.png' },
    { name: 'GrindCore Ultra', price: 4780, currency: '$', url: 'cutter.png' },
    { name: 'Tenderizer Max', price: 3950, currency: '$', url: 'cutter.png' },
    { name: 'PigSplitter', price: 5070, currency: '$', url: 'cutter.png' },
    { name: 'MooCutter', price: 4160, currency: '$', url: 'cutter.png' },
    { name: 'CarniKiller 3X', price: 5340, currency: '$', url: 'cutter.png' },
    { name: 'Sliceomatic', price: 4000, currency: '$', url: 'cutter.png' },
    { name: 'BeefChop 1.2', price: 3790, currency: '$', url: 'cutter.png' },
    { name: 'Chopzilla Mini', price: 3880, currency: '$', url: 'cutter.png' },
    { name: 'LardLaser 100', price: 4990, currency: '$', url: 'cutter.png' },
  ],

  slicers: [
    { name: 'BrisketBasher', price: 4100, currency: '$', url: 'cutter.png' },
    { name: 'HogHacker', price: 3600, currency: '$', url: 'cutter.png' },
    { name: 'SliceDroid', price: 5200, currency: '$', url: 'cutter.png' },
    { name: 'Mincerator 9K', price: 4420, currency: '$', url: 'cutter.png' },
    { name: 'AutoTender 300', price: 4780, currency: '$', url: 'cutter.png' },
    { name: 'GigaChop Pro', price: 5010, currency: '$', url: 'cutter.png' },
    { name: 'HamHammer', price: 3890, currency: '$', url: 'cutter.png' },
    { name: 'FatSplit X1', price: 4720, currency: '$', url: 'cutter.png' },
    { name: 'SausageSurge', price: 4850, currency: '$', url: 'cutter.png' },
    { name: 'Carnage Core', price: 5210, currency: '$', url: 'cutter.png' },
    { name: 'VealSlicer Z2', price: 4150, currency: '$', url: 'cutter.png' },
    { name: 'ShredMatic', price: 4010, currency: '$', url: 'cutter.png' },
    { name: 'PrimeGrinder', price: 4950, currency: '$', url: 'cutter.png' },
    { name: 'TenderThrasher', price: 4600, currency: '$', url: 'cutter.png' },
    { name: 'ChopLine XR', price: 3900, currency: '$', url: 'cutter.png' },
    { name: 'Grindinator 4000', price: 5120, currency: '$', url: 'cutter.png' },
    { name: 'SliceFlux', price: 4300, currency: '$', url: 'cutter.png' },
    { name: 'CutPro XT', price: 4460, currency: '$', url: 'cutter.png' },
    { name: 'UltraBeef Blade', price: 4600, currency: '$', url: 'cutter.png' },
    { name: 'MinceWave Z', price: 4040, currency: '$', url: 'cutter.png' },
    { name: 'BladeStorm', price: 4700, currency: '$', url: 'cutter.png' },
    { name: 'ChopDrill 2', price: 4190, currency: '$', url: 'cutter.png' },
    { name: 'MeatMill Pro', price: 4260, currency: '$', url: 'cutter.png' },
    { name: 'SlicerEdge', price: 4950, currency: '$', url: 'cutter.png' },
    { name: 'PiggyMince', price: 4300, currency: '$', url: 'cutter.png' },
    { name: 'SliceCrush Turbo', price: 5100, currency: '$', url: 'cutter.png' },
  ],

  grinders: [
    { name: 'MegaTender Pro', price: 4480, currency: '$', url: 'cutter.png' },
    { name: 'BladeFlexor', price: 4920, currency: '$', url: 'cutter.png' },
    { name: 'GigaSlicer T', price: 4620, currency: '$', url: 'cutter.png' },
    { name: 'FatLine 800', price: 4740, currency: '$', url: 'cutter.png' },
    { name: 'GrindStreak', price: 4550, currency: '$', url: 'cutter.png' },
    { name: 'MooMaster 600', price: 4980, currency: '$', url: 'cutter.png' },
    { name: 'UltraSlicer 3D', price: 4430, currency: '$', url: 'cutter.png' },
    { name: 'PrimeMincer 1K', price: 4830, currency: '$', url: 'cutter.png' },
    { name: 'SausageChop Max', price: 4610, currency: '$', url: 'cutter.png' },
    { name: 'T-Bone Hacker', price: 4750, currency: '$', url: 'cutter.png' },
    { name: 'CowCutter XL', price: 4890, currency: '$', url: 'cutter.png' },
    { name: 'PorkGrind X7', price: 4120, currency: '$', url: 'cutter.png' },
    { name: 'GrindMate Pro', price: 5010, currency: '$', url: 'cutter.png' },
    { name: 'AutoSlaughter', price: 4870, currency: '$', url: 'cutter.png' },
    { name: 'CowCrush 22', price: 4680, currency: '$', url: 'cutter.png' },
    { name: 'GrindBot 9X', price: 4390, currency: '$', url: 'cutter.png' },
    { name: 'MinceDestroyer', price: 4550, currency: '$', url: 'cutter.png' },
    { name: 'BladeFury', price: 5090, currency: '$', url: 'cutter.png' },
    { name: 'BeefCrunch XR', price: 4190, currency: '$', url: 'cutter.png' },
    { name: 'ShredForce Z', price: 4300, currency: '$', url: 'cutter.png' },
    { name: 'HamLine 77', price: 4460, currency: '$', url: 'cutter.png' },
    { name: 'Carnistroyer', price: 4210, currency: '$', url: 'cutter.png' },
    { name: 'AutoCut X-Prime', price: 4960, currency: '$', url: 'cutter.png' },
    { name: 'Chopforce 9T', price: 4780, currency: '$', url: 'cutter.png' },
    { name: 'PorkSlicer Turbo', price: 4890, currency: '$', url: 'cutter.png' },
    { name: 'Slicerator Pro', price: 4570, currency: '$', url: 'cutter.png' },
    { name: 'MinceFlux Z', price: 4820, currency: '$', url: 'cutter.png' },
    { name: 'Tenderizer XR', price: 4610, currency: '$', url: 'cutter.png' },
    { name: 'GrindMachine Pro', price: 4760, currency: '$', url: 'cutter.png' },
    { name: 'SlaughterCore 3D', price: 5020, currency: '$', url: 'cutter.png' },
  ],

  fillers: [
    { name: 'BaconBlade Max', price: 4920, currency: '$', url: 'cutter.png' },
    { name: 'GrindForge Elite', price: 4500, currency: '$', url: 'cutter.png' },
    { name: 'UltraGrinder 6K', price: 5050, currency: '$', url: 'cutter.png' },
    { name: 'MinceReactor', price: 4880, currency: '$', url: 'cutter.png' },
    { name: 'MeatStorm Z9', price: 4785, currency: '$', url: 'cutter.png' },
    { name: 'SliceVortex 2000', price: 4655, currency: '$', url: 'cutter.png' },
    { name: 'GrindShift X', price: 4899, currency: '$', url: 'cutter.png' },
    { name: 'TenderBox XR', price: 4999, currency: '$', url: 'cutter.png' },
    { name: 'PigRipper T9', price: 4155, currency: '$', url: 'cutter.png' },
    { name: 'CowCrash 404', price: 4800, currency: '$', url: 'cutter.png' },
    { name: 'RibRipper Pro', price: 5030, currency: '$', url: 'cutter.png' },
    { name: 'HamHack Ultra', price: 4575, currency: '$', url: 'cutter.png' },
    { name: 'SteakSmash Z', price: 4700, currency: '$', url: 'cutter.png' },
    { name: 'ChopTornado', price: 4622, currency: '$', url: 'cutter.png' },
    { name: 'MincePulse', price: 4440, currency: '$', url: 'cutter.png' },
    { name: 'AutoChop Pro', price: 4230, currency: '$', url: 'cutter.png' },
    { name: 'BladeFusion X7', price: 4900, currency: '$', url: 'cutter.png' },
    { name: 'BrisketBlast 2', price: 4720, currency: '$', url: 'cutter.png' },
    { name: 'MooCrush 600', price: 4555, currency: '$', url: 'cutter.png' },
    { name: 'SausageTwister', price: 4980, currency: '$', url: 'cutter.png' },
    { name: 'LoinLacerator', price: 4911, currency: '$', url: 'cutter.png' },
    { name: 'SliceVibe Z2', price: 4855, currency: '$', url: 'cutter.png' },
    { name: 'TenderStorm Pro', price: 4360, currency: '$', url: 'cutter.png' },
    { name: 'Cowinator 3000', price: 4699, currency: '$', url: 'cutter.png' },
    { name: 'BladeSnap XR', price: 4601, currency: '$', url: 'cutter.png' },
    { name: 'CutForce Max', price: 4310, currency: '$', url: 'cutter.png' },
    { name: 'HamDicer', price: 4075, currency: '$', url: 'cutter.png' },
    { name: 'GrindCannon', price: 5090, currency: '$', url: 'cutter.png' },
    { name: 'MinceCrafter Z', price: 4455, currency: '$', url: 'cutter.png' },
    { name: 'TenderX Blast', price: 4710, currency: '$', url: 'cutter.png' },
    { name: 'PigSplatter', price: 4955, currency: '$', url: 'cutter.png' },
    { name: 'BeefBlade Prime', price: 4990, currency: '$', url: 'cutter.png' },
    { name: 'SteakBreaker', price: 4545, currency: '$', url: 'cutter.png' },
    { name: 'AutoRind XR', price: 4422, currency: '$', url: 'cutter.png' },
    { name: 'SlabSlicer', price: 4770, currency: '$', url: 'cutter.png' },
    { name: 'ChopLine Prime', price: 4688, currency: '$', url: 'cutter.png' },
    { name: 'ShredSlayer', price: 4533, currency: '$', url: 'cutter.png' },
    { name: 'CowCut 1.1', price: 4801, currency: '$', url: 'cutter.png' },
    { name: 'FatGrinder XT', price: 4910, currency: '$', url: 'cutter.png' },
  ],

  mixers: [
    { name: 'CutPro XT', price: 4460, currency: '$', url: 'cutter.png' },

    { name: 'SliceSpin Turbo', price: 4520, currency: '$', url: 'cutter.png' },
    { name: 'Mincedroid', price: 4460, currency: '$', url: 'cutter.png' },
    { name: 'AutoSlice 360', price: 4822, currency: '$', url: 'cutter.png' },
    { name: 'HamCruncher', price: 4735, currency: '$', url: 'cutter.png' },
    { name: 'GrindFury', price: 4970, currency: '$', url: 'cutter.png' },
    { name: 'MeatSnap T4', price: 4125, currency: '$', url: 'cutter.png' },
    {
      name: 'UltraMincer Elite',
      price: 4880,
      currency: '$',
      url: 'cutter.png',
    },
    { name: 'ChopTrek XR', price: 4675, currency: '$', url: 'cutter.png' },
    { name: 'PorkSmasher 77', price: 4532, currency: '$', url: 'cutter.png' },
    { name: 'Tenderizer GX', price: 4550, currency: '$', url: 'cutter.png' },
    { name: 'SliceFusion Lite', price: 4199, currency: '$', url: 'cutter.png' },
    { name: 'BeefCannon 2', price: 4930, currency: '$', url: 'cutter.png' },
    { name: 'RindStorm Z4', price: 4375, currency: '$', url: 'cutter.png' },
    { name: 'AutoGrind X', price: 4260, currency: '$', url: 'cutter.png' },
    { name: 'SausageShocker', price: 4788, currency: '$', url: 'cutter.png' },
    { name: 'MinceMonster', price: 4602, currency: '$', url: 'cutter.png' },
    { name: 'LoinLaser XR', price: 4932, currency: '$', url: 'cutter.png' },
    { name: 'ShredderMate', price: 4495, currency: '$', url: 'cutter.png' },
    { name: 'GrindStomp T5', price: 4885, currency: '$', url: 'cutter.png' },
    { name: 'PigPounder', price: 4740, currency: '$', url: 'cutter.png' },
    { name: 'MooTornado', price: 4515, currency: '$', url: 'cutter.png' },
    { name: 'AutoLacerator', price: 4105, currency: '$', url: 'cutter.png' },
    { name: 'ChopTwist Ultra', price: 4440, currency: '$', url: 'cutter.png' },
    { name: 'BeefMauler', price: 4845, currency: '$', url: 'cutter.png' },
    { name: 'GrindTower Z', price: 4652, currency: '$', url: 'cutter.png' },
    { name: 'BladeWhip XR', price: 4475, currency: '$', url: 'cutter.png' },
    { name: 'MeatBolt', price: 4205, currency: '$', url: 'cutter.png' },
    { name: 'PiggyTwister', price: 4811, currency: '$', url: 'cutter.png' },
    { name: 'HamRipper 8', price: 4981, currency: '$', url: 'cutter.png' },
    { name: 'UltraGrindMaster', price: 4995, currency: '$', url: 'cutter.png' },
    { name: 'ChopSwipe', price: 4212, currency: '$', url: 'cutter.png' },
    { name: 'FatDriller', price: 4898, currency: '$', url: 'cutter.png' },
    { name: 'SliceDrum', price: 4925, currency: '$', url: 'cutter.png' },
    { name: 'Grindinator Mini', price: 4322, currency: '$', url: 'cutter.png' },
    { name: 'MinceRush', price: 4582, currency: '$', url: 'cutter.png' },
    { name: 'SausageCutter', price: 4875, currency: '$', url: 'cutter.png' },
    { name: 'AutoSlicer Pro', price: 4830, currency: '$', url: 'cutter.png' },
    { name: 'MooFury XR', price: 4777, currency: '$', url: 'cutter.png' },
    { name: 'ChopTide 3D', price: 4990, currency: '$', url: 'cutter.png' },
    { name: 'BladeSurge', price: 4566, currency: '$', url: 'cutter.png' },
    { name: 'BeefBlaster XR', price: 4639, currency: '$', url: 'cutter.png' },
    { name: 'PiggyNator', price: 4430, currency: '$', url: 'cutter.png' },
    { name: 'MincerBeast Z', price: 4744, currency: '$', url: 'cutter.png' },
    { name: 'ShredSlammer', price: 4209, currency: '$', url: 'cutter.png' },
    { name: 'CutDrill', price: 4340, currency: '$', url: 'cutter.png' },
    { name: 'ChopLancer XR', price: 4505, currency: '$', url: 'cutter.png' },
    { name: 'FatSliceMaster', price: 4791, currency: '$', url: 'cutter.png' },
    { name: 'BladeCrasher', price: 4945, currency: '$', url: 'cutter.png' },
    { name: 'AutoShred Turbo', price: 4905, currency: '$', url: 'cutter.png' },
    { name: 'LoinWhirl T2', price: 4551, currency: '$', url: 'cutter.png' },
    { name: 'Tenderizer Force', price: 4799, currency: '$', url: 'cutter.png' },
    { name: 'GrindZilla Mini', price: 4439, currency: '$', url: 'cutter.png' },
    { name: 'RibTwister 500', price: 4704, currency: '$', url: 'cutter.png' },
    { name: 'CowVortex', price: 4975, currency: '$', url: 'cutter.png' },
    { name: 'MeatCraft Prime', price: 4892, currency: '$', url: 'cutter.png' },
  ],
}

// Виробники
// (
//   LASKA, AUTOTHERM, REX-TECHNOLOGIE, BORGO, TREIF, MAJA, TIPPER TIE, INJECT STAR, KITTNER, SESOTEC
// )
// Ін'єктування та масажування
// (
//   Ін'єктори, масажери
// )
// Приготування фаршу
// (
//   Вовчки,
//   Куттери,
//   Блокорізки
// )
// Порціонування
// (
//   Шприці,
//   Кліпсатори,
//   Перекрутчики,
// )
// Термічна обробка
// (
//   Варочні Камери,
//   Димогенератори,
// )
// Мийка
// (
//   Мийки для ящиків,
// )
// Інше обладнання
// (
//   Льодогенератори,
//   Шкурозїемні машини,
//   Металодетектори,
//   Гігіена
//   Шпигорезка
// )

const itemsToSell = {
  Виробники: [
    { LASKA: [{ 'Приготування фаршу': ['Вовчки', 'Куттери', 'Блокорізки'] }] },
    {
      AUTOTHERM: [{ 'Термічна обробка': ['Варочні Камери', 'Димогенератори'] }],
    },
    { 'REX-TECHNOLOGIE': [{ Порціонування: ['Шприці'] }] },
    { BORGO: ['перев’язувальні машини'] },
    { TREIF: [{ 'Інше обладнання': ['Шпигорізки'] }] },
    {
      MAJA: [{ 'Інше обладнання': ['Шкурозїемні машини', 'Льодогенератори'] }],
    },
    { 'TIPPER TIE': [{ Порціонування: ['Кліпсатори'] }] },
    {
      'INJECT STAR': [
        { 'Ін`єктування та масажування': ['Ін`єктори', 'масажери'] },
      ],
    },
  ],
}
